### ISSUE TITLE
Single click works sporatically

### ISSUE THREAD

**Issue by mjwheatley** [barbatus/ionic2-meteor#10]
Running on a mobile device.

I do not experience this issue with running the example application, but when I tried to implement this package in my own application I did.

I would click the menu button, then try to click on one of the menu items and nothing would happen.  I found that the page would open if I double clicked however.

I think it has something to do with gesture recognition (touch swipe).  I found that if I swipe the menu open or closed I can single click again only once, then it's back to double clicking.  I do not experience this issue with a vanilla Ionic2 application.  Only running an ionic2-meteor application.

Has anyone else experienced this anomaly?

**Comment by barbatus** [comment]
Ionic 2 adds its own solution to fix well-known 300ms click delay issue on the mobile Web
platforms. From other side, fastclick package that fixes the same, goes as a dependency of the mobile-experience, a package that is added by default to any Meteor app. So, you'll have to remove it from the app in order to avoid conflicts with Ionic 2. You can re-add, though, any other dependency, like "launch-screen", separately if you need to

This is a note from the http://www.angular-meteor.com/tutorials/socially/angular2/ionic

**Comment by mjwheatley** [comment]
Ah yes, I remember reading that note once upon a time.  This indeed was the culprit and removing the mobile-experience package to remove fastclick fixed the issue.
