### ISSUE TITLE
barbatus:angular2 and barbatus:typescript

### ISSUE THREAD

**Issue by nelsonec87** [barbatus/ionic2-meteor#19]
Hi, I trying to use meteor1.3 + angular2 + ionic2 + npm modules (client).

I've set up the meteor project following the angular-meteor tutorial. It works fine. I added 

`npm install angular2-google-maps`

and it worked fine too. Then I  tried to add `barbatus:ionic2-meteor`, getting:

`error: conflict: two packages included in the app (barbatus:angular2 and barbatus:typescript) are both trying to handle *.ts`

If I remove `angular2-compilers`, it "compiles", but the npm modules stop working.

Thank you for your work in the open source community! Really useful projects!

**Comment by mjwheatley** [comment]
It doesn't appear that you can use this package with Meteor 1.3. This package requires systemjs and the node modules use commonjs.  You will have to use the ionic-framework NPM module with Meteor 1.3 instead of this package.
I have created a [starter project](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter) that you can reference for project configuration.  (**Warning**: I do not have it working on mobile devices yet.)

**Comment by nelsonec87** [comment]
Thank you!

I used the Ionic2 CLI to solve the problem, like in [angular-meteor whatsapp exemple](http://www.angular-meteor.com/tutorials/whatsapp/ionic/bootstrapping).

You can check the [repo](https://github.com/nelsonec87/ionic2-meteor-seed) here.

**Comment by mjwheatley** [comment]
@nelsonec87 does that setup allow you to use the hot code push feature to deliver client updates?

**Comment by nelsonec87** [comment]
@mjwheatley It probably doesn't work out of the box, since it would require a native plugin to cache the files. 

I think it would require to add the cordova plugin manually (the same used by meteor).

Or use [another plugin](https://github.com/nordnet/cordova-hot-code-push)
